apiVersion: v1
kind: ConfigMap
metadata:
  name: entrypoint
  namespace: {{ .Values.namespace }}
binaryData:
  entrypoint.sh:
    {{- .Files.Get "files/entrypoint.sh" | b64enc | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: evil-pod
  namespace: {{ .Values.namespace }}
binaryData:
  evil-pod.sh:
    {{- .Files.Get "files/evil-pod/evil-pod.sh" | b64enc | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: evil-pod-entrypoint
  namespace: {{ .Values.namespace }}
binaryData:
  evil-pod-entrypoint.sh:
    {{- .Files.Get "files/evil-pod/evil-pod-entrypoint.sh" | b64enc | indent 4 }}
