apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: aiq-agent-k8s-role
rules:
  - apiGroups: [ "" ]
    resources: [ "pods/exec" ]
    verbs: [ "get", "list", "create" ]
  - apiGroups: [ "" ]
    resources: [ "pods/log" ]
    verbs: [ "get", "list", "create" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "endpoints" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "limitranges" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "persistentvolumeclaims" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "podtemplates" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "replicationcontrollers" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "resourcequotas" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "serviceaccounts" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "services" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
#  - apiGroups: [ "" ]
#    resources: [ "daemonsets.apps" ]
#    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
#  - apiGroups: [ "" ]
#    resources: [ "deployments.apps" ]
#    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
#  - apiGroups: [ "" ]
#    resources: [ "replicasets.apps" ]
#    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
#  - apiGroups: [ "" ]
#    resources: [ "statefulsets.apps" ]
#    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
#  - apiGroups: [ "" ]
#    resources: [ "cronjobs.batch" ]
#    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
#  - apiGroups: [ "" ]
#    resources: [ "jobs.batch" ]
#    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
#  - apiGroups: [ "" ]
#    resources: [ "daemonsets.extensions" ]
#    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
#  - apiGroups: [ "" ]
#    resources: [ "deployments.extensions" ]
#    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
#  - apiGroups: [ "" ]
#    resources: [ "ingresses.extensions" ]
#    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
#  - apiGroups: [ "" ]
#    resources: [ "networkpolicies.extensions" ]
#    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
#  - apiGroups: [ "" ]
#    resources: [ "replicasets.extensions" ]
#    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
#  - apiGroups: [ "" ]
#    resources: [ "ingresses.networking.k8s.io" ]
#    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
#  - apiGroups: [ "" ]
#    resources: [ "networkpolicies.networking.k8s.io" ]
#    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
#  - apiGroups: [ "" ]
#    resources: [ "clusterrolebindings.rbac.authorization.k8s.io" ]
#    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
#  - apiGroups: [ "" ]
#    resources: [ "clusterroles.rbac.authorization.k8s.io" ]
#    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
#  - apiGroups: [ "" ]
#    resources: [ "rolebindings.rbac.authorization.k8s.io" ]
#    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
#  - apiGroups: [ "" ]
#    resources: [ "roles.rbac.authorization.k8s.io" ]
#    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
#  - apiGroups: [ "" ]
#    resources: [ "leases.coordination.k8s.io" ]
#    verbs: [ "get", "list" ]
#  - apiGroups: [ "" ]
#    resources: [ "endpointslices.discovery.k8s.io" ]
#    verbs: [ "get", "list" ]
#  - apiGroups: [ "" ]
#    resources: [ "events.events.k8s.io" ]
#    verbs: [ "get", "list" ]
#  - apiGroups: [ "" ]
#    resources: [ "poddisruptionbudgets.policy" ]
#    verbs: [ "get", "list" ]
#  - apiGroups: [ "" ]
#    resources: [ "csistoragecapacities.storage.k8s.io" ]
#    verbs: [ "get", "list" ]