apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
binaryData:
  config.yml:
    {{ .Files.Get "files/config.yml" | b64enc | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: entrypoint
binaryData:
  entrypoint.sh:
    {{- .Files.Get "files/entrypoint.sh" | b64enc | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: evil-pod
binaryData:
  evil-pod.sh:
    {{- .Files.Get "files/evil-pod/evil-pod.sh" | b64enc | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: evil-pod-entrypoint
binaryData:
  evil-pod-entrypoint.sh:
    {{- .Files.Get "files/evil-pod/evil-pod-entrypoint.sh" | b64enc | indent 4 }}
