apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: aiq-agent-k8s-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aiq-agent-k8s-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Values.namespace }}