name: Lint and Test Charts

on:
  push:
    paths:
      - '**'

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    name: lint-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@main
        with:
          command: lint
          config: .github/ct.yaml
